# Generated by Django 5.1.2 on 2024-10-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_order_status_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
