# Generated by Django 5.1.2 on 2024-10-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
