# Generated by Django 5.1.2 on 2024-10-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_order_shipping_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
